version: '3'

services:
  db:
    ports: []
    user: "1000:1000"
    networks:
      - app_net
  localstack:
    image: localstack/localstack:latest
    env_file: .env
    ports:
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock.s
    volumes:
      - ./test/helpers/:/docker-entrypoint-initaws.d
      - .localstack:/tmp/localstack
    networks:
      - app_net
  web:
    image: delight:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST="true"
    command: bash -c "pytest -vv --ds=delight.settings test/"
    ports: []
    depends_on:
      - db
      - localstack
    networks:
      - app_net

networks:
  app_net:
    driver: bridge