version: '3'

services:
  db:
    ports: []
  localstack:
    image: localstack/localstack:latest
    env_file: .env
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock.s
    volumes:
      - ./test/helpers/s3.sh:/docker-entrypoint-initaws.d/s3.sh
      - .localstack:/tmp/localstack
  web:
    image: delight:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST="true"
    command: bash -c "pytest -vv --ds=delight.settings test/"
    ports: []
    depends_on:
      - db
      - localstack
