# Generated by Django 2.2.4 on 2020-05-09 18:04

import apps.s3.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.s3.utils.get_filepath, validators=[apps.s3.utils.check_file_size])),
                ('type', models.CharField(choices=[('ALI', 'album_image'), ('ARI', 'artist_image'), ('SI', 'song_image'), ('SF', 'song_file'), ('PI', 'post_image'), ('UI', 'user_image')], max_length=12, unique=True)),
            ],
        ),
    ]
