# Generated by Django 2.2.4 on 2020-05-10 20:30

import apps.s3.storages
import apps.s3.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=apps.s3.storages.StaticStorage(), upload_to=apps.s3.utils.get_filepath, validators=[apps.s3.utils.check_file_size]),
        ),
    ]
