# Generated by Django 2.2.4 on 2020-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_auto_20200510_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('ALI', 'album_image'), ('ARI', 'artist_image'), ('SI', 'song_image'), ('SF', 'song_file'), ('PI', 'post_image'), ('UI', 'user_image')], max_length=12),
        ),
    ]
