# Generated by Django 2.2.4 on 2020-04-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user', '0008_auto_20200408_1811'), ('user', '0009_image_post'), ('user', '0010_auto_20200408_1953')]

    dependencies = [
        ('user', '0007_remove_user_liked_songs'),
        ('media', '0006_auto_20190923_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('albums', models.ManyToManyField(blank=True, related_name='posts', to='media.Album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('playlists', models.ManyToManyField(blank=True, related_name='posts', to='user.Playlist')),
                ('songs', models.ManyToManyField(blank=True, related_name='posts', to='media.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.Post')),
            ],
        ),
    ]
