# Generated by Django 2.2.4 on 2020-04-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user', '0011_auto_20200408_2058'), ('user', '0012_auto_20200408_2115')]

    dependencies = [
        ('user', '0010_auto_20200408_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
