# Generated by Django 2.2.4 on 2020-05-07 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200507_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=10),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
