# Generated by Django 2.2.4 on 2020-05-09 18:00

import delight.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200507_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=10, validators=[delight.validators.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='d52s6jdjsch27.cloudfront.net/default/user_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
    ]
