# Generated by Django 2.2.4 on 2020-05-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_playlist_songs_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_playlist_name_per_user_constraint'),
        ),
    ]
