# Generated by Django 2.2.4 on 2020-05-12 21:16

import delight.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_playlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.URLField(default='https://d52s6jdjsch27.cloudfront.net/default/media_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://d52s6jdjsch27.cloudfront.net/default/user_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
    ]
