# Generated by Django 2.2.4 on 2020-05-09 18:00

import delight.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20190923_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.URLField(default='d52s6jdjsch27.cloudfront.net/default/media_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.URLField(default='d52s6jdjsch27.cloudfront.net/default/user_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.URLField(validators=[delight.validators.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(default='d52s6jdjsch27.cloudfront.net/default/media_logo.png', validators=[delight.validators.CustomURLValidator]),
        ),
    ]
