# Generated by Django 2.2.4 on 2020-05-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20200509_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs_amount',
        ),
    ]
