from apps.media.serializers.album import AlbumShortInfoSerializer as SearchAlbumShortInfoSerializer
from apps.media.serializers.artist import ArtistShortInfoSerializer as SearchArtistShortInfoSerializer
from apps.search_old.serializer_files.song import SearchSongShortInfoSerializer
